### ISSUE TITLE
We don't wrap the main function unless it's called "main"

### ISSUE THREAD

**Issue by DavidPoliakoff** [LLNL/GOTCHA#81] opened 2019-03-21 22:37 UTC
In our translations.c, we have the ability to wrap main, in spite of the weirdness of libc_start_main. It would be nice if we had some way to instead of wrapping main, wrap the first argument to libc_start_main, something I think we can do in Gotcha.

**Comment by mwkrentel** [comment] 2019-07-31 04:58
@DavidPoliakoff Have you tried this?  Can you successfully wrap either
main or __libc_start_main?

I tired this and I couldn't get it to work, and I don't think this is
even possible with gotcha.

I think __libc_start_main is handled special from the other dynamic
symbols.  The loader plucks the address for start main before you have
a chance to run any code.  So, writing the GOT table from gotcha_wrap
isn't going to work.

I don't know if this is even possible from gotcha or not, but if it
is, I think it requires something beyond writing the GOT table.

Btw, this doesn't really matter because wrapping __libc_start_main
doesn't work.  But the signature for start main is different on
powerpc.  translations.c only has the x86 version.

**Comment by mplegendre** [comment] 2019-07-31 16:02
Yes, we do test wrapping main.  The entry point address used by the loader is for the __init symbol.  The __libc_start_main traditionally goes through the GOT table.  If you have a different results, we could use a reproducer or patch to the the main-wrapping support (see https://github.com/LLNL/GOTCHA/commit/a8bff73bf6559f1b891878bdb25d345f73fe8b59).

**Comment by mwkrentel** [comment] 2019-07-31 18:49
@mplegendre Nope, I tried the wrap_main unit test, and it still
doesn't work for me.

It built cleanly.

```
$ ls -l
drwxr-xr-x 4 krentel hpc  4096 Jul 31 13:16 CMakeFiles
-rw-r--r-- 1 krentel hpc   237 Jul 31 13:14 CMakeLists.txt
-rw-r--r-- 1 krentel hpc   443 Jul 31 13:15 CTestTestfile.cmake
-rw-r--r-- 1 krentel hpc  9136 Jul 31 13:15 Makefile
-rw-r--r-- 1 krentel hpc    95 Jul 31 13:14 app.c
-rw-r--r-- 1 krentel hpc  1174 Jul 31 13:15 cmake_install.cmake
-rw-r--r-- 1 krentel hpc   837 Jul 31 13:35 lib.c
-rw-r--r-- 1 krentel hpc   129 Jul 31 13:14 lib.h
-rwxr-xr-x 1 krentel hpc 12984 Jul 31 13:36 libmain_functions.so
-rwxr-xr-x 1 krentel hpc 11104 Jul 31 13:36 main

$ ldd main 
        linux-vdso.so.1 (0x00007ffeae265000)
        libmain_functions.so => /home/krentel/gotcha/temp/gotcha/test/wrap_main/libmain_functions.so (0x00007f23389d8000)
        libgotcha.so.1 => /home/krentel/gotcha/temp/gotcha/src/libgotcha.so.1 (0x00007f23387cd000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f23383f8000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f2338bda000)
```

But when I run main, it runs the init ctor, gotcha_wrap succeeds, but
the main wrapper never gets called and main returns 1, not the 0 that
the wrapper tries to reset it to.  This is consistent with the results
I've seen on my own where I was trying to wrap __libc_start_main.

```
$ ./main 
In attr constructor func
In main main

$ echo $?
1
```

Have you or @DavidPoliakoff actually run this and it works?
Can you suggest a LLNL machine where it works for you?

I'm running on Fedora 26.  I'm wondering if RH uses a different
startup sequence that breaks your wrapping.

**Comment by DavidPoliakoff** [comment] 2019-07-31 19:35
@mwkrentel , I know this worked quite a while ago, I'm not sure why it doesn't work now. Sorry I can't dig in on this one for you, I know I slapped together that code quite quickly, odds are there's a way around it.

**Comment by mwkrentel** [comment] 2019-07-31 20:31
Ok, I think I see what's happening and this is a problem.
I tried the wrap main test on various systems, old and new.

```
nancy    RedHat 6.x     glibc 2.12  --  works
les      RedHat 7.x     glibc 2.17  --  works
mic      Fedora 26      glibc 2.25  --  no wrapping
follis   Ubuntu 18.04   glibc 2.27  --  no wrapping
```

My theory is that something changed between glibc 2.17 and 2.25 that
breaks your way of wrapping main or __libc_start_main.  So, it
currently works on "old" systems, up through RH 7.x, but going
forward, it's not going to work.

I say this is a problem because it causes trouble for the "always on"
profiling we've discussed.  I don't see a clean way of wrapping main
without LD_PRELOAD or Dyninst.

**Comment by mplegendre** [comment] 2019-07-31 20:36
It's likely an interface change.  We'll probably just need to go research the new interface, and change what we wrap if the glibc version is after a certain revision.  To investigate.

**Comment by hariharan-devarajan** [comment] 2023-07-20 05:41
#116 Fixes this issue.

**Comment by hariharan-devarajan** [comment] 2023-07-20 05:41
Closing for now unless someone again finds this issue in other machines.

**Closed by hariharan-devarajan** 2023-07-20 05:41 UTC
